# Apache daemon handler
#
# Parameters:
# - apache_daemon: the name of the Apache daemon
---
- name: restart apache
  service:
    name: "{{ apache_daemon }}"
    state: restarted
  when: apache_daemon_restart
